### ISSUE TITLE
uri related code cleanup

### ISSUE THREAD

**Issue by AnotherDaniel** [eclipse-uprotocol/up-rust#40]
I am working to clean up and pull together code belonging to UUri, specifically:
- make issues during serialization visible to the user - use TryFrom and Result<> instead of empty default objects and Option<>  
- move the serialization/deserialization code directly into the TryFrom implementations, this gets rid of all the *serializer stuff while making the whole thing more rust-like
- general little cleanups and simplifications

This work will base on #18, so depends on that being merged.

**Comment by PLeVasseur** [comment]
I found an issue with ambiguity in the usage of id vs up when we're serializing / desrializing to and from Micro URI form.

So #18 is waiting on this [up-core-api #102](https://github.com/eclipse-uprotocol/up-core-api/pull/102) change to get merged, so that the validation logic and I guess serialization and deserialization logic in general can be reflected.

So I guess #18 may do a bit of what you're suggesting, but very lightly. Just more or less trying to get the Micro URI validation in. Lemme know if you have any concerns on overlap over on that PR when I can update it.

**Comment by AnotherDaniel** [comment]
LongUri cleanup done via #49  -  Will start on MicroUri soon

**Comment by evshary** [comment]
Hi @AnotherDaniel 
@PLeVasseur and I discussed about the serialization of micro Uri [here](https://github.com/eclipse-uprotocol/up-client-zenoh-rust/pull/2#discussion_r1501858724).
We think it would be good if up-rust can support the API to serialize UAuthority alone.
The requirement is that we need to extract UAuthority to generate the Zenoh key for the uStreamer scenario.
Do you think it can be also included in your cleanup? Thank you!

**Comment by AnotherDaniel** [comment]
@evshary sure! Will include that - only for micro serialization, correct?

**Comment by evshary** [comment]
> @evshary sure! Will include that - only for micro serialization, correct?

Yes, I think so.

**Comment by AnotherDaniel** [comment]
Microuri cleanup here: #54

**Comment by AnotherDaniel** [comment]
#54 merged, so this is done
