### ISSUE TITLE
UMesageBuilder::with_message_id()

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-rust#88]
The factory methods that build request(), response(), notificaiton(), and publish() should within the belly create the message ID as there is no real benefit to force the developer to call with_message_id(). 
Take a look at the up-java [UAttributeBuilder.java](https://github.com/eclipse-uprotocol/up-java/blob/main/src/main/java/org/eclipse/uprotocol/transport/builder/UAttributesBuilder.java), the factory methods when they instantiate the UAttributeBuilder object, the UUID is automatically created and populated. I don't think we need to add the flexibility to add different types of UUID, we're only supporting the one defined in the spec now.

**Comment by PLeVasseur** [comment]
btw -- I think I missed this when bringing in the `UUIDBuilder` singleton. In the past when it was not a singleton, the design you're proposing wouldn't have been possible.

imho the simplest way to accomplish this would probably be to to, within `UMessageBuilder::build()` put a call to `UUIDBuilder::build()` and assign the returned `UUID` to the attributes.id field.

WDYT @sophokles73?

**Comment by sophokles73** [comment]
Yes, that had been the original idea anyway (passing in a UUIDBuilder). Now that we have the singleton, we can automatically create the message ID as part of `build` as you point out correctly. We can still keep the `with_message_id` function in order to let people set it manually and then, when building the message, simply check if `id` is None or Some ...

**Comment by PLeVasseur** [comment]
> Yup, on it 👍

Resolved in #90
